name: Deploy Vanilla JavaScript PWA Checklist App

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Clear Parcel cache
        run: rm -rf .parcel-cache

      - name: Build Project
        run: |
          npm run build
          ls -l ./docs # Verify contents of the build folder (docs in this case)
          cat ./docs/index.html # Check if the build output is correct

      - name: Setup Git config
        run: |
          git config --global user.name "theITGuy825"
          git config --global user.email "theITGuy825@users.noreply.github.com"

      - name: Pull latest changes from main branch
        run: |
          git fetch origin main
          git checkout main
          git pull origin main

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-main@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs  # Pointing to the 'docs' folder which contains the final build
          force_orphan: true   # Ensure a clean deploy (no history from other branches)
          allow_empty_commit: true # Allow for an empty commit if necessary

      - name: Upload logs
        run: |
          mkdir logs
          echo "Logs uploaded on $(date)" > logs/summary.log
          tar -czf logs.tar.gz logs
        continue-on-error: true
